function mpc = 6busww_toy
%6BUSWW_TOY  reduction toy case, existing network only.
%   Generated by analysis/build_toy_case.jl from the planning workbook.
%   Demand scaling 0.018; wind and solar are negative load.
%   Planning-candidate lines and generators are NOT included.
%   Pmin is 0: it is a commitment floor, every solver here relaxes it,
%   and build_tx_case's base DC-OPF does not. Real floor in network_gens.csv.
mpc.version = '2';
mpc.baseMVA = 100;

%% bus data
%	bus_i	type	Pd	Qd	Gs	Bs	area	Vm	Va	baseKV	zone	Vmax	Vmin
mpc.bus = [
	1	3	0.0000	0	0	0	1	1	0	230	1	1.1	0.9;
	2	2	0.0000	0	0	0	1	1	0	230	1	1.1	0.9;
	3	2	0.0000	0	0	0	1	1	0	230	1	1.1	0.9;
	4	1	8.4362	0	0	0	1	1	0	230	1	1.1	0.9;
	5	1	-9.1699	0	0	0	1	1	0	230	1	1.1	0.9;
	6	1	27.2203	0	0	0	1	1	0	230	1	1.1	0.9;
];

%% generator data
%	bus	Pg	Qg	Qmax	Qmin	Vg	mBase	status	Pmax	Pmin	Pc1	Pc2	Qc1min	Qc1max	Qc2min	Qc2max	ramp_agc	ramp_10	ramp_30	ramp_q	apf
mpc.gen = [
	1	0	0	0	0	1	100	1	200.0000	0	0	0	0	0	0	0	0	0	0	0	0;
	2	0	0	0	0	1	100	1	150.0000	0	0	0	0	0	0	0	0	0	0	0	0;
	3	0	0	0	0	1	100	1	180.0000	0	0	0	0	0	0	0	0	0	0	0	0;
];

%% branch data
%	fbus	tbus	r	x	b	rateA	rateB	rateC	ratio	angle	status	angmin	angmax
mpc.branch = [
	1	2	0	0.200000	0	40.0000	40.0000	40.0000	0	0	1	-360	360;
	1	4	0	0.200000	0	60.0000	60.0000	60.0000	0	0	1	-360	360;
	1	5	0	0.300000	0	40.0000	40.0000	40.0000	0	0	1	-360	360;
	2	3	0	0.250000	0	40.0000	40.0000	40.0000	0	0	1	-360	360;
	2	4	0	0.100000	0	60.0000	60.0000	60.0000	0	0	1	-360	360;
	2	5	0	0.300000	0	30.0000	30.0000	30.0000	0	0	1	-360	360;
	2	6	0	0.200000	0	90.0000	90.0000	90.0000	0	0	1	-360	360;
	3	5	0	0.260000	0	70.0000	70.0000	70.0000	0	0	1	-360	360;
	3	6	0	0.100000	0	80.0000	80.0000	80.0000	0	0	1	-360	360;
	4	5	0	0.400000	0	20.0000	20.0000	20.0000	0	0	1	-360	360;
	5	6	0	0.300000	0	40.0000	40.0000	40.0000	0	0	1	-360	360;
];

%% generator cost data
mpc.gencost = [
	2	0	0	3	0	30.450000	0;
	2	0	0	3	0	47.155200	0;
	2	0	0	3	0	96.121800	0;
];
